import type { Animal } from './animals';

/**
 * Animali dei pacchetti a pagamento aggiunti dopo la prima versione. Diventano
 * disponibili nell'app appena esiste la loro illustrazione "sole" (vedi
 * animal-images.json, generato da `npm run images`); fino ad allora compaiono
 * come "in arrivo" nel loro pacchetto.
 */
export const EXTRA_ANIMALS: Animal[] = [
  // ---------------- Fattoria ----------------
  {
    id: 'pecora',
    name: 'Pecora',
    emoji: '🐑',
    pack: 'fattoria',
    tagline: 'Previsioni soffici come la lana',
    promptSubject: 'a fluffy sheep with cream white wool and a dark grey face',
    phrases: {
      sole: ['Sole pieno: oggi mi tosano e vado in spiaggia leggera!', 'Bel tempo: brucare al sole è il mio sport preferito.'],
      notte: ['Notte serena: stasera conto gli umani per addormentarmi.', 'Cielo stellato e lana calda. Beeeeh-lla notte!'],
      nuvoloso: ['Nuvoloso: le nuvole sembrano mie cugine.', 'Cielo grigio, lana bianca. Contrasto perfetto.'],
      pioggia: ['Piove: niente di peggio della lana bagnata. Ombrello, subito!', 'Pioggia: oggi profumo di maglione ammollo.'],
      temporale: ['Temporale: tutto il gregge sotto la tettoia!', 'Tuoni! Mi nascondo dietro la pecora più grossa.'],
      neve: ['Neve: finalmente nessuno mi trova, sono mimetizzata!', 'Nevica: il mio cappotto di lana è pronto da mesi.'],
      nebbia: ['Nebbia: ho perso il gregge... beeeh?', 'Non vedo niente, seguo il campanaccio.'],
      vento: ['Vento forte: rischio di volare via come un batuffolo.', 'Raffiche! Ho la lana tutta cotonata.'],
      caldo: ['Caldo torrido: mi tolgo il maglione, anche se è la mia pelle.', 'Troppo caldo per la lana: chi mi tosa?'],
      freddo: ['Gelo: ecco perché porto la lana tutto l\'anno.', 'Sotto zero: io sto benissimo, voi coprite bene.'],
    },
  },
  {
    id: 'cavallo',
    name: 'Cavallo',
    emoji: '🐴',
    pack: 'fattoria',
    tagline: 'Previsioni al galoppo',
    promptSubject: 'a friendly chestnut brown pony with a blonde mane',
    phrases: {
      sole: ['Sole: criniera al vento e galoppata nei prati!', 'Bella giornata: oggi niente stalla, si trotta fuori.'],
      notte: ['Notte serena: dormo in piedi, come i veri professionisti.', 'Cielo stellato: sogno un prato infinito di carote.'],
      nuvoloso: ['Nuvoloso: tempo da passeggiata al passo.', 'Cielo grigio, ma la criniera è sempre in piega.'],
      pioggia: ['Piove: zoccoli nel fango e coperta impermeabile.', 'Pioggia: oggi il maneggio si trasforma in piscina.'],
      temporale: ['Temporale: tutti nella stalla, al trotto!', 'Tuoni! Faccio un nitrito e mi nascondo nel fieno.'],
      neve: ['Neve: oggi tiro la slitta, chi sale?', 'Nevica: criniera bianca e zoccoli freschi.'],
      nebbia: ['Nebbia: so la strada a memoria, fidatevi.', 'Non vedo il recinto, ma sento l\'odore della biada.'],
      vento: ['Vento forte: criniera spettinata da copertina!', 'Raffiche: oggi galoppo anche controvento.'],
      caldo: ['Caldo torrido: secchio d\'acqua fresca e ombra, grazie.', 'Troppo caldo per correre: oggi solo passeggio.'],
      freddo: ['Gelo: coperta di lana e fieno caldo.', 'Sotto zero: sbuffo nuvolette come un drago.'],
    },
  },
  {
    id: 'asinello',
    name: 'Asinello',
    emoji: '🫏',
    pack: 'fattoria',
    tagline: 'Testardo, ma non sbaglia mai',
    promptSubject: 'a little grey donkey with very big ears',
    phrases: {
      sole: ['Sole: oggi non mi muovo, mi abbronzo le orecchie.', 'Bel tempo: ih-oh, giornata perfetta!'],
      notte: ['Notte serena: ragliata alla luna e poi a nanna.', 'Cielo stellato: con queste orecchie sento le stelle.'],
      nuvoloso: ['Nuvoloso: tempo da asino pensieroso.', 'Cielo grigio: oggi faccio il testardo, non esco.'],
      pioggia: ['Piove: le orecchie fanno da grondaia.', 'Pioggia: ombrello grande, per coprire le orecchie.'],
      temporale: ['Temporale: io resto qui, e non mi spostate!', 'Tuoni! Ih-oh... cioè, aiuto.'],
      neve: ['Neve: orecchie gelate, cuore contento.', 'Nevica: oggi porto i bambini sullo slittino.'],
      nebbia: ['Nebbia: le mie orecchie sono antenne radar.', 'Non vedo niente, ma sento tutto.'],
      vento: ['Vento forte: con queste orecchie potrei volare.', 'Raffiche: le orecchie fanno da vela!'],
      caldo: ['Caldo torrido: mi sventolo con le orecchie.', 'Troppo caldo: oggi non porto niente, sciopero!'],
      freddo: ['Gelo: paraorecchie extra-large, grazie.', 'Sotto zero: fieno e coperta, il resto domani.'],
    },
  },

  // ---------------- Mare e Polo ----------------
  {
    id: 'polpo',
    name: 'Polpo',
    emoji: '🐙',
    pack: 'mare',
    tagline: 'Otto braccia, zero dubbi',
    promptSubject: 'a round purple octopus with big shiny eyes',
    phrases: {
      sole: ['Sole: crema solare su tutti e otto i tentacoli!', 'Bel tempo: oggi tintarella sullo scoglio.'],
      notte: ['Notte serena: mi rintano nella mia conchiglia preferita.', 'Cielo stellato: sembrano stelle marine in cielo.'],
      nuvoloso: ['Nuvoloso: tempo perfetto per un pisolino in tana.', 'Cielo grigio: coloro le nuvole con l\'inchiostro.'],
      pioggia: ['Piove: per me è solo mare che scende dall\'alto.', 'Pioggia: otto ombrelli, uno per tentacolo.'],
      temporale: ['Temporale: tutti giù in fondo al mare!', 'Tuoni! Spruzzo inchiostro e scompaio.'],
      neve: ['Neve: otto guanti da infilare, ci vorrà un po\'.', 'Nevica: faccio un pupazzo con otto braccia.'],
      nebbia: ['Nebbia: come nuotare nell\'inchiostro.', 'Non vedo niente, tasto in giro coi tentacoli.'],
      vento: ['Vento forte: mi aggrappo con tutte le ventose.', 'Raffiche: tengo stretti otto cappelli.'],
      caldo: ['Caldo torrido: torno in acqua, ciao!', 'Troppo caldo: rischio di diventare frittura.'],
      freddo: ['Gelo: otto sciarpe, e non bastano.', 'Sotto zero: mi abbraccio da solo, tanto ho le braccia.'],
    },
  },
  {
    id: 'delfino',
    name: 'Delfino',
    emoji: '🐬',
    pack: 'mare',
    tagline: 'Il meteorologo più simpatico dell\'oceano',
    promptSubject: 'a happy light blue baby dolphin standing upright on its tail',
    phrases: {
      sole: ['Sole: salti e capriole tra le onde!', 'Bel tempo: oggi gara di tuffi, vinco io.'],
      notte: ['Notte serena: dormo con un occhio solo, l\'altro guarda le stelle.', 'Cielo stellato: canto la ninna nanna alle balene.'],
      nuvoloso: ['Nuvoloso: il mare è grigio, ma io sono sempre allegro.', 'Cielo coperto: tempo da gioco sott\'acqua.'],
      pioggia: ['Piove: tanto io sono già bagnato!', 'Pioggia: le gocce fanno il solletico al mare.'],
      temporale: ['Temporale: tutti al largo, lontano dalle onde!', 'Tuoni! Mi immergo e aspetto il sole.'],
      neve: ['Neve: brrr, oggi nuoto verso il caldo.', 'Nevica sul mare: spettacolo da fischio!'],
      nebbia: ['Nebbia: per fortuna ho il sonar incorporato.', 'Non vedo niente, ma sento tutto con l\'eco.'],
      vento: ['Vento forte: onde perfette per il surf!', 'Raffiche: salto più in alto del solito.'],
      caldo: ['Caldo torrido: venite tutti in acqua!', 'Troppo caldo a riva: il mare vi aspetta.'],
      freddo: ['Gelo: oggi migro verso il Mediterraneo.', 'Sotto zero: nuoto veloce per scaldarmi.'],
    },
  },
  {
    id: 'granchio',
    name: 'Granchio',
    emoji: '🦀',
    pack: 'mare',
    tagline: 'Previsioni di lato, ma precise',
    promptSubject: 'a chubby red crab with big round eyes and big claws',
    phrases: {
      sole: ['Sole: passeggiata laterale sulla spiaggia!', 'Bel tempo: le chele sono pronte per il castello di sabbia.'],
      notte: ['Notte serena: mi infilo nella sabbia e buonanotte.', 'Cielo stellato: conto le stelle con le chele.'],
      nuvoloso: ['Nuvoloso: tempo da granchio brontolone.', 'Cielo grigio: oggi cammino di lato, e di malumore.'],
      pioggia: ['Piove: chela sinistra ombrello, chela destra stivale.', 'Pioggia: pozzanghere da attraversare di lato.'],
      temporale: ['Temporale: mi rintano sotto lo scoglio!', 'Tuoni! Pizzico il primo che passa dalla paura.'],
      neve: ['Neve: guantoni sulle chele, si fa il pupazzo.', 'Nevica: oggi passeggio di lato, ma lentamente.'],
      nebbia: ['Nebbia: tanto io cammino sempre di lato.', 'Non vedo niente, avanzo a tentoni... di lato.'],
      vento: ['Vento forte: mi ancoro alla sabbia con le chele.', 'Raffiche: rotolo sulla spiaggia come una palla.'],
      caldo: ['Caldo torrido: sono già rosso, non serve la tintarella.', 'Troppo caldo: buca nella sabbia bagnata, subito.'],
      freddo: ['Gelo: guscio duro, ma il freddo passa lo stesso.', 'Sotto zero: chele nelle tasche, se le avessi.'],
    },
  },
  {
    id: 'tartaruga',
    name: 'Tartaruga',
    emoji: '🐢',
    pack: 'mare',
    tagline: 'Lenta, ma arriva sempre prima del temporale',
    promptSubject: 'a little green sea turtle with a patterned shell, standing upright',
    phrases: {
      sole: ['Sole: tintarella sulla spiaggia, con calma.', 'Bel tempo: oggi arrivo al mare... forse domani.'],
      notte: ['Notte serena: mi ritiro nel guscio e buonanotte.', 'Cielo stellato: le stelle sono vecchie quasi come me.'],
      nuvoloso: ['Nuvoloso: perfetto, niente fretta nemmeno oggi.', 'Cielo grigio: guscio caldo e pensieri lenti.'],
      pioggia: ['Piove: il guscio è il miglior ombrello del mondo.', 'Pioggia: tanto io nuoto benissimo.'],
      temporale: ['Temporale: testa dentro il guscio, ci vediamo dopo.', 'Tuoni! Io sono al sicuro, ho la casa addosso.'],
      neve: ['Neve: io vado in letargo, svegliatemi ad aprile.', 'Nevica: berretto sulla testa e guscio imbottito.'],
      nebbia: ['Nebbia: vado piano, come sempre.', 'Non vedo niente, ma tanto non corro.'],
      vento: ['Vento forte: mi faccio portare a riva dalle onde.', 'Raffiche: il guscio non vola, io resto qui.'],
      caldo: ['Caldo torrido: torno in acqua lentamente... molto lentamente.', 'Troppo caldo: anche il guscio scotta!'],
      freddo: ['Gelo: guscio chiuso, riscaldamento acceso.', 'Sotto zero: cioccolata calda, da sorseggiare piano.'],
    },
  },

  {
    id: 'orca',
    name: 'Orca',
    emoji: '🐋',
    pack: 'mare',
    tagline: 'La regina degli oceani (e delle previsioni)',
    promptSubject: 'a cute chubby baby orca whale, black and white, standing upright on its tail',
    phrases: {
      sole: ['Sole: salto fuori dall\'acqua solo per farmi una foto!', 'Bel tempo: oggi il mare è una tavola, si nuota in famiglia.'],
      notte: ['Notte serena: canto alla luna con tutto il branco.', 'Cielo stellato: dormo galleggiando, una pinna alla volta.'],
      nuvoloso: ['Nuvoloso: in bianco e nero mi sento perfettamente intonata.', 'Cielo grigio: tempo da tuffi pensierosi.'],
      pioggia: ['Piove: tanto io sono già bagnata dalla nascita!', 'Pioggia: le gocce mi fanno il solletico sulla pinna.'],
      temporale: ['Temporale: tutte giù in profondità, lì sotto è calmo.', 'Tuoni! Anche la regina del mare preferisce aspettare.'],
      neve: ['Neve: finalmente clima da casa mia, al Polo!', 'Nevica: faccio il pupazzo di neve su un iceberg.'],
      nebbia: ['Nebbia: per fortuna mi oriento con l\'eco.', 'Non vedo niente, ma sento il branco che canta.'],
      vento: ['Vento forte: onde enormi, si fa surf!', 'Raffiche: spruzzo dallo sfiatatoio e il vento lo porta via.'],
      caldo: ['Caldo torrido: torno al Polo, ci vediamo a settembre.', 'Troppo caldo: anche il mare sembra una vasca da bagno.'],
      freddo: ['Gelo: per me è una giornata di primavera.', 'Sotto zero: io sto benissimo, voi copritevi!'],
    },
  },

  // ---------------- Bosco e Stagno ----------------
  {
    id: 'volpe',
    name: 'Volpe',
    emoji: '🦊',
    pack: 'bosco',
    tagline: 'Furba anche con le nuvole',
    promptSubject: 'a little orange fox with a big fluffy white-tipped tail',
    phrases: {
      sole: ['Sole: coda al vento e passeggiata nel bosco.', 'Bel tempo: oggi faccio la volpe in vacanza.'],
      notte: ['Notte serena: la mia ora preferita per curiosare.', 'Cielo stellato: mi arrotolo nella coda e sogno.'],
      nuvoloso: ['Nuvoloso: tempo da volpe furba, niente sole negli occhi.', 'Cielo grigio: perfetto per nascondersi.'],
      pioggia: ['Piove: la coda fa da ombrello, ve l\'avevo detto.', 'Pioggia: salto le pozzanghere con eleganza.'],
      temporale: ['Temporale: tana, coda sul naso e aspetto.', 'Tuoni! Anche le volpi furbe hanno paura.'],
      neve: ['Neve: salto a tuffo nella neve fresca!', 'Nevica: le mie impronte disegnano il bosco.'],
      nebbia: ['Nebbia: il mio naso vede meglio degli occhi.', 'Non vedo niente, ma so già dov\'è la merenda.'],
      vento: ['Vento forte: la coda sventola come una bandiera.', 'Raffiche: annuso mille odori nuovi.'],
      caldo: ['Caldo torrido: pelliccia rossa e 35 gradi, che idea.', 'Troppo caldo: all\'ombra del pino più grande.'],
      freddo: ['Gelo: la coda è la mia sciarpa.', 'Sotto zero: arrotolata nella tana, al calduccio.'],
    },
  },
  {
    id: 'riccio',
    name: 'Riccio',
    emoji: '🦔',
    pack: 'bosco',
    tagline: 'Pungente solo con il brutto tempo',
    promptSubject: 'a round little hedgehog with brown spines and a tan face',
    phrases: {
      sole: ['Sole: aculei al sole e pancia all\'aria.', 'Bel tempo: oggi passeggio tra le foglie.'],
      notte: ['Notte serena: è ora di uscire a cercare lombrichi!', 'Cielo stellato: il riccio notturno è in servizio.'],
      nuvoloso: ['Nuvoloso: tempo da riccio pensieroso.', 'Cielo grigio: mi arrotolo e aspetto.'],
      pioggia: ['Piove: gli aculei bucano l\'ombrello, peccato.', 'Pioggia: perfetta per trovare lumache!'],
      temporale: ['Temporale: palla di aculei e non ci sono per nessuno.', 'Tuoni! Mi arrotolo stretto stretto.'],
      neve: ['Neve: io vado in letargo, svegliatemi a primavera.', 'Nevica: dormo sotto le foglie, buon inverno.'],
      nebbia: ['Nebbia: tanto io cammino a naso.', 'Non vedo niente, attenti a non pestarmi!'],
      vento: ['Vento forte: rotolo via come una castagna!', 'Raffiche: gli aculei fischiano nel vento.'],
      caldo: ['Caldo torrido: ciotolina d\'acqua, per favore.', 'Troppo caldo: mi nascondo tra l\'erba umida.'],
      freddo: ['Gelo: letargo anticipato, ciao a tutti.', 'Sotto zero: copertina di foglie e sonno profondo.'],
    },
  },
  {
    id: 'gufo',
    name: 'Gufo',
    emoji: '🦉',
    pack: 'bosco',
    tagline: 'Saggio di giorno, sveglio di notte',
    promptSubject: 'a cute round brown owl with big eyes',
    phrases: {
      sole: ['Sole: troppa luce, occhiali da sole obbligatori.', 'Bel tempo: io dormirei, ma oggi vale la pena.'],
      notte: ['Notte serena: finalmente il mio turno! Uh-uh!', 'Cielo stellato: perfetto per una lezione di astronomia.'],
      nuvoloso: ['Nuvoloso: luce soffusa, ideale per i miei occhi.', 'Cielo grigio: tempo da gufo che legge un libro.'],
      pioggia: ['Piove: piume bagnate, umore bagnato.', 'Pioggia: resto nel tronco a leggere.'],
      temporale: ['Temporale: chiudo gli occhioni e aspetto.', 'Tuoni! Persino il gufo saggio si spaventa.'],
      neve: ['Neve: il bosco bianco è bellissimo dall\'alto.', 'Nevica: piumino naturale, nessun problema.'],
      nebbia: ['Nebbia: con questi occhi vedo comunque tutto.', 'Non vedete niente? Io sì. Uh-uh.'],
      vento: ['Vento forte: mi tengo forte al ramo.', 'Raffiche: le piume si spettinano, che disastro.'],
      caldo: ['Caldo torrido: di giorno dormo all\'ombra.', 'Troppo caldo: esco solo dopo il tramonto.'],
      freddo: ['Gelo: mi gonfio come un pallone di piume.', 'Sotto zero: piume arruffate e tè caldo.'],
    },
  },
  {
    id: 'scoiattolo',
    name: 'Scoiattolo',
    emoji: '🐿️',
    pack: 'bosco',
    tagline: 'Previsioni a tutta velocità',
    promptSubject: 'a cute red squirrel with a big bushy tail',
    phrases: {
      sole: ['Sole: corsa tra i rami e nocciole a volontà!', 'Bel tempo: oggi faccio scorta di ghiande.'],
      notte: ['Notte serena: abbraccio la coda e dormo nel nido.', 'Cielo stellato: sogno una montagna di nocciole.'],
      nuvoloso: ['Nuvoloso: tempo perfetto per nascondere le ghiande.', 'Cielo grigio: corro lo stesso, non so stare fermo.'],
      pioggia: ['Piove: la coda fa da ombrello, come sempre.', 'Pioggia: resto nel nido a contare le provviste.'],
      temporale: ['Temporale: tutti nel tronco, con le scorte!', 'Tuoni! Lancio una nocciola e scappo.'],
      neve: ['Neve: dove ho nascosto le ghiande? Non ricordo.', 'Nevica: menomale che ho fatto la scorta.'],
      nebbia: ['Nebbia: salto da un ramo all\'altro alla cieca.', 'Non vedo niente, ma le nocciole le trovo.'],
      vento: ['Vento forte: il ramo balla e io con lui!', 'Raffiche: volo come uno scoiattolo volante.'],
      caldo: ['Caldo torrido: coda sopra la testa come un ombrellone.', 'Troppo caldo: oggi corro solo all\'ombra.'],
      freddo: ['Gelo: coda-coperta e nocciole in dispensa.', 'Sotto zero: nel nido, a sgranocchiare.'],
    },
  },

  // ---------------- Amici di casa ----------------
  {
    id: 'coniglio',
    name: 'Coniglio',
    emoji: '🐰',
    pack: 'casa',
    tagline: 'Previsioni a saltelli',
    promptSubject: 'a cute fluffy white bunny with pink inner ears',
    phrases: {
      sole: ['Sole: saltelli nel prato e carote al sole!', 'Bel tempo: oggi orecchie dritte e tanta allegria.'],
      notte: ['Notte serena: nella tana, con la mia carota peluche.', 'Cielo stellato: la luna sembra una carota rotonda.'],
      nuvoloso: ['Nuvoloso: le nuvole sembrano conigli giganti.', 'Cielo grigio: oggi salto più piano.'],
      pioggia: ['Piove: orecchie giù e ombrello su.', 'Pioggia: salto le pozzanghere, una dopo l\'altra.'],
      temporale: ['Temporale: tutti in tana, e di corsa!', 'Tuoni! Il mio naso trema più del solito.'],
      neve: ['Neve: mi mimetizzo perfettamente, cercatemi!', 'Nevica: impronte di coniglio dappertutto.'],
      nebbia: ['Nebbia: seguo l\'odore delle carote.', 'Non vedo niente, salto alla cieca!'],
      vento: ['Vento forte: le orecchie fanno da elica!', 'Raffiche: tenetemi, sto per decollare.'],
      caldo: ['Caldo torrido: sdraiato sulle piastrelle fresche.', 'Troppo caldo: carote ghiacciate, per favore.'],
      freddo: ['Gelo: pelliccia folta e tana calda.', 'Sotto zero: mi accoccolo con gli altri conigli.'],
    },
  },
  {
    id: 'criceto',
    name: 'Criceto',
    emoji: '🐹',
    pack: 'casa',
    tagline: 'Guance piene, previsioni giuste',
    promptSubject: 'a chubby golden hamster with round cheeks',
    phrases: {
      sole: ['Sole: giro sulla ruota fino al tramonto!', 'Bel tempo: guance piene di semi e buonumore.'],
      notte: ['Notte serena: è ora di correre sulla ruota!', 'Cielo stellato: io sono sveglissimo, voi dormite pure.'],
      nuvoloso: ['Nuvoloso: tempo da tana e trucioli.', 'Cielo grigio: riempio le guance per sicurezza.'],
      pioggia: ['Piove: ombrellino piccolo piccolo.', 'Pioggia: resto in casetta a sgranocchiare.'],
      temporale: ['Temporale: mi nascondo nei trucioli!', 'Tuoni! Le guance si gonfiano dallo spavento.'],
      neve: ['Neve: palline di neve grandi come me.', 'Nevica: cappellino di lana e semi di girasole.'],
      nebbia: ['Nebbia: seguo il profumo dei semi.', 'Non vedo niente, ma la dispensa la trovo.'],
      vento: ['Vento forte: tenetemi, sono leggerissimo!', 'Raffiche: rotolo come una pallina dorata.'],
      caldo: ['Caldo torrido: piastrella fresca e niente ruota.', 'Troppo caldo: oggi solo semi e riposo.'],
      freddo: ['Gelo: nido di trucioli extra-soffice.', 'Sotto zero: mi arrotolo come un panino.'],
    },
  },
  {
    id: 'pappagallo',
    name: 'Pappagallo',
    emoji: '🦜',
    pack: 'casa',
    tagline: 'Ripete le previsioni finché non le impari',
    promptSubject: 'a colorful green parrot with a yellow and red face',
    phrases: {
      sole: ['Sole! Sole! Che bella giornata! Squak!', 'Bel tempo: piume colorate al sole, che spettacolo.'],
      notte: ['Notte serena: buonanotte, buonanotte, buonanotte!', 'Cielo stellato: copritemi la gabbia, grazie.'],
      nuvoloso: ['Nuvoloso! Nuvoloso! L\'ho già detto? Nuvoloso!', 'Cielo grigio: per fortuna le mie piume colorano tutto.'],
      pioggia: ['Piove! Piove! Ombrello! Squak!', 'Pioggia: bagnetto gratis per le piume.'],
      temporale: ['Temporale! Aiuto! Aiuto! Squak!', 'Tuoni: faccio finta di essere coraggioso.'],
      neve: ['Neve! Freddo! Freddo! Vengo dai tropici, io!', 'Nevica: piumino e sciarpa, subito.'],
      nebbia: ['Nebbia! Dove siete? Dove siete?', 'Non vedo niente, ma vi sento, chiacchieroni.'],
      vento: ['Vento! Vento! Volo senza sbattere le ali!', 'Raffiche: le piume sono tutte all\'insù.'],
      caldo: ['Caldo! Caldo! Mi ricorda casa mia!', 'Caldo torrido: finalmente clima tropicale.'],
      freddo: ['Gelo! Brrr! Brrr! Lo ripeto: brrr!', 'Sotto zero: torno ai tropici, chi viene?'],
    },
  },

  // ---------------- Esotici ----------------
  {
    id: 'scimmia',
    name: 'Scimmia',
    emoji: '🐵',
    pack: 'esotici',
    tagline: 'Previsioni da un ramo all\'altro',
    promptSubject: 'a cute brown monkey with a light tan face',
    phrases: {
      sole: ['Sole: banana, liana e occhiali da sole!', 'Bel tempo: oggi salto da un albero all\'altro.'],
      notte: ['Notte serena: abbraccio la mia banana e dormo.', 'Cielo stellato: la luna sembra una banana piegata.'],
      nuvoloso: ['Nuvoloso: tempo da scimmia annoiata.', 'Cielo grigio: faccio facce buffe per tirarvi su.'],
      pioggia: ['Piove: foglia gigante come ombrello.', 'Pioggia: la giungla fa la doccia.'],
      temporale: ['Temporale: tutti giù dagli alberi!', 'Tuoni! Mi copro gli occhi con le mani.'],
      neve: ['Neve: io sono una scimmia tropicale, cos\'è questa roba?', 'Nevica: palle di neve contro tutti!'],
      nebbia: ['Nebbia: non vedo la liana, salto lo stesso!', 'Non vedo niente, ma le banane le trovo.'],
      vento: ['Vento forte: dondolo come un\'altalena!', 'Raffiche: mi aggrappo alla coda di qualcuno.'],
      caldo: ['Caldo torrido: frullato di banana ghiacciato.', 'Troppo caldo anche per la giungla!'],
      freddo: ['Gelo: maglione di lana e banana calda.', 'Sotto zero: abbracci di gruppo tra scimmie.'],
    },
  },
  {
    id: 'giraffa',
    name: 'Giraffa',
    emoji: '🦒',
    pack: 'esotici',
    tagline: 'Vede il meteo prima di tutti',
    promptSubject: 'a cute baby giraffe with orange spots',
    phrases: {
      sole: ['Sole: lo vedo per prima, sono la più alta!', 'Bel tempo: foglie fresche in cima all\'albero.'],
      notte: ['Notte serena: con il collo quasi tocco le stelle.', 'Cielo stellato: dormo in piedi, cinque minuti alla volta.'],
      nuvoloso: ['Nuvoloso: ho la testa tra le nuvole, letteralmente.', 'Cielo grigio: da quassù le nuvole sono vicinissime.'],
      pioggia: ['Piove: servirebbe un ombrello lungo tre metri.', 'Pioggia: la testa si bagna per prima.'],
      temporale: ['Temporale: abbasso il collo, meglio non sporgersi!', 'Tuoni! Sono troppo alta per nascondermi.'],
      neve: ['Neve: sciarpa lunghissima, finalmente serve.', 'Nevica: i fiocchi mi cadono negli occhi.'],
      nebbia: ['Nebbia: io sto sopra la nebbia, vedo benissimo!', 'Non vedete niente? Salite sul mio collo.'],
      vento: ['Vento forte: il collo ondeggia come un bambù.', 'Raffiche: tenete fermo il mio cappello lassù.'],
      caldo: ['Caldo torrido: l\'ombra della giraffa è grande, venite.', 'Troppo caldo: acqua fresca, ma devo chinarmi tanto.'],
      freddo: ['Gelo: quanti metri di sciarpa mi servono?', 'Sotto zero: il collo è lungo, il freddo anche.'],
    },
  },
  {
    id: 'leone',
    name: 'Leone',
    emoji: '🦁',
    pack: 'esotici',
    tagline: 'Il re della savana e del meteo',
    promptSubject: 'a cute lion cub with a fluffy golden mane',
    phrases: {
      sole: ['Sole: il re si abbronza sulla roccia!', 'Bel tempo: ruggito di felicità. Roar!'],
      notte: ['Notte serena: anche i re hanno bisogno di dormire.', 'Cielo stellato: le stelle sono la mia corona.'],
      nuvoloso: ['Nuvoloso: il re è di cattivo umore.', 'Cielo grigio: pisolino reale, non disturbare.'],
      pioggia: ['Piove: criniera bagnata, dignità a rischio.', 'Pioggia: anche i re usano l\'ombrello.'],
      temporale: ['Temporale: il re non ha paura... quasi.', 'Tuoni! Ruggisco più forte del tuono!'],
      neve: ['Neve: criniera piena di fiocchi, che stile.', 'Nevica: il re della savana non è abituato.'],
      nebbia: ['Nebbia: il mio ruggito vi guida a casa.', 'Non vedo i sudditi, ma li sento.'],
      vento: ['Vento forte: criniera al vento da film!', 'Raffiche: la mia criniera è un disastro reale.'],
      caldo: ['Caldo torrido: pisolino all\'ombra dell\'acacia.', 'Troppo caldo anche per il re della savana.'],
      freddo: ['Gelo: la criniera tiene caldo, il resto no.', 'Sotto zero: coperta reale e camomilla.'],
    },
  },
];
